const recipes = [
  {
    id: 1,
    recipe_title: "Crispy Onion Rings",
    author_name: "John Smith",
    publish_date: "April 10, 2025",
    time: "15 mins",
    chill_time: "0 mins",
    category: "Appetizer",
    main_image: "../../../Public/assets/RecipeDetails/crispy1.jpg",
    instruction_image: "../../../Public/assets/RecipeDetails/crispy2.jpg",
    calories: "250",
    protein: "4g",
    carbohydrates: "30g",
    fat: "12g",
    sugars: "5g",
    calcium: "6%",
    nutrition_note: "Values are per serving (4 onion rings).",
    recipe_description:
      "Golden and crispy onion rings, perfect as a snack or side dish, with a light and crunchy batter.",
    point_item1: "Crispy Texture",
    point_item2: "Quick to Prepare",
    point_item3: "Kid-Friendly",
    point_item4: "Perfect for Parties",
    ingredients: [
      "2 large onions, sliced into rings",
      "1 cup all-purpose flour",
      "1 cup buttermilk",
      "1 cup breadcrumbs",
      "1 tsp paprika",
      "Oil for frying",
    ],
    instructions: [
      "Slice onions into 1/4-inch thick rings and separate.",
      "Dip onion rings in buttermilk, then coat in flour mixed with paprika.",
      "Dip again in buttermilk, then coat with breadcrumbs.",
      "Fry in hot oil until golden brown, about 2-3 minutes per side.",
      "Drain on paper towels and serve hot.",
    ],
    tip1_title: "Even Coating",
    tip1_content: "Ensure each ring is fully coated for maximum crunch.",
    tip2_title: "Oil Temperature",
    tip2_content: "Keep oil at 350°F for perfect frying.",
    tip3_title: "Serve Immediately",
    tip3_content: "Onion rings are best enjoyed fresh and hot.",
    variation1_title: "Spicy Onion Rings",
    variation1_content: "Add cayenne pepper to the flour for a spicy kick.",
    variation1_image: "../../../Public/assets/RecipeDetails/crispy3.jpg",
    variation2_title: "Beer-Battered Onion Rings",
    variation2_content: "Use beer instead of buttermilk for a richer flavor.",
    variation2_image: "../../../Public/assets/RecipeDetails/crispy4.jpg",
    variation3_title: "Baked Onion Rings",
    variation3_content: "Bake at 425°F for a lighter version.",
    variation3_image: "../../../Public/assets/RecipeDetails/crispy5.jpg",
  },
  {
    id: 2,
    recipe_title: "Toast with Tomato and Hummus",
    author_name: "Emma Wilson",
    publish_date: "April 12, 2025",
    time: "10 mins",
    chill_time: "0 mins",
    category: "Breakfast",
    main_image: "../../../Public/assets/RecipeDetails/toast1.jpg",
    instruction_image: "../../../Public/assets/RecipeDetails/toast2.jpeg",
    calories: "200",
    protein: "6g",
    carbohydrates: "25g",
    fat: "8g",
    sugars: "3g",
    calcium: "8%",
    nutrition_note: "Values are per serving (1 slice).",
    recipe_description:
      "A quick and healthy breakfast option with creamy hummus and fresh tomatoes on toasted bread.",
    point_item1: "Quick and Easy",
    point_item2: "Healthy Start",
    point_item3: "Customizable",
    point_item4: "Vegan-Friendly",
    ingredients: [
      "2 slices whole-grain bread",
      "1/2 cup hummus",
      "1 tomato, sliced",
      "1 tsp olive oil",
      "Pinch of salt and pepper",
      "Fresh basil leaves",
    ],
    instructions: [
      "Toast the bread slices until golden.",
      "Spread a generous layer of hummus on each slice.",
      "Top with tomato slices and drizzle with olive oil.",
      "Season with salt, pepper, and garnish with basil leaves.",
      "Serve immediately.",
    ],
    tip1_title: "Fresh Ingredients",
    tip1_content: "Use ripe tomatoes for the best flavor.",
    tip2_title: "Bread Choice",
    tip2_content: "Sourdough or whole-grain bread adds extra flavor.",
    tip3_title: "Add Protein",
    tip3_content: "Sprinkle with hemp seeds for a protein boost.",
    variation1_title: "Avocado Hummus Toast",
    variation1_content: "Add mashed avocado for extra creaminess.",
    variation1_image: "../../../Public/assets/RecipeDetails/toast3.jpeg",
    variation2_title: "Spicy Hummus Toast",
    variation2_content: "Use spicy hummus for a bold twist.",
    variation2_image: "../../../Public/assets/RecipeDetails/toast4.jpeg",
    variation3_title: "Mediterranean Toast",
    variation3_content: "Add feta and olives for a Mediterranean flair.",
    variation3_image: "../../../Public/assets/RecipeDetails/toast5.jpeg",
  },
  {
    id: 3,
    recipe_title: "Ham, Egg, and Spinach Rollups",
    author_name: "Michael Chen",
    publish_date: "April 14, 2025",
    time: "20 mins",
    chill_time: "0 mins",
    category: "Breakfast",
    main_image: "../../../Public/assets/RecipeDetails/ham1.jpg",
    instruction_image: "../../../Public/assets/RecipeDetails/ham2.jpeg",
    calories: "300",
    protein: "18g",
    carbohydrates: "15g",
    fat: "20g",
    sugars: "2g",
    calcium: "10%",
    nutrition_note: "Values are per serving (2 rollups).",
    recipe_description:
      "Savory rollups filled with ham, scrambled eggs, and fresh spinach, perfect for a hearty breakfast.",
    point_item1: "Protein-Packed",
    point_item2: "Portable Meal",
    point_item3: "Quick Prep",
    point_item4: "Great for Brunch",
    ingredients: [
      "4 large eggs",
      "4 slices ham",
      "1 cup fresh spinach",
      "1/4 cup shredded cheddar cheese",
      "1 tbsp butter",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Scramble eggs with salt and pepper in butter until just set.",
      "Lay out ham slices and place spinach leaves on each.",
      "Spoon scrambled eggs onto spinach and sprinkle with cheese.",
      "Roll up the ham slices tightly.",
      "Serve warm or at room temperature.",
    ],
    tip1_title: "Egg Texture",
    tip1_content: "Don’t overcook eggs to keep them soft.",
    tip2_title: "Cheese Options",
    tip2_content: "Try Swiss or mozzarella for different flavors.",
    tip3_title: "Make Ahead",
    tip3_content: "Prepare rollups the night before and reheat.",
    variation1_title: "Turkey Rollups",
    variation1_content: "Swap ham for turkey slices.",
    variation1_image: "../../../Public/assets/RecipeDetails/ham3.avif",
    variation2_title: "Veggie Rollups",
    variation2_content: "Add bell peppers for extra crunch.",
    variation2_image: "../../../Public/assets/RecipeDetails/ham4.jpeg",
    variation3_title: "Spicy Rollups",
    variation3_content: "Add hot sauce to the eggs for a kick.",
    variation3_image: "../../../Public/assets/RecipeDetails/ham5.jpeg",
  },
  {
    id: 4,
    recipe_title: "Chicken Ranch Wrap",
    author_name: "Sarah Johnson",
    publish_date: "April 16, 2025",
    time: "15 mins",
    chill_time: "0 mins",
    category: "Lunch",
    main_image: "../../../Public/assets/RecipeDetails/chicken1.webp",
    instruction_image: "../../../Public/assets/RecipeDetails/chicken2.jpg",
    calories: "350",
    protein: "25g",
    carbohydrates: "30g",
    fat: "15g",
    sugars: "4g",
    calcium: "10%",
    nutrition_note: "Values are per serving (1 wrap).",
    recipe_description:
      "A fresh and flavorful wrap filled with grilled chicken, ranch dressing, and crisp veggies, ideal for a quick lunch.",
    point_item1: "Quick Lunch",
    point_item2: "Customizable",
    point_item3: "Fresh Ingredients",
    point_item4: "Portable",
    ingredients: [
      "2 large flour tortillas",
      "1 cup grilled chicken, sliced",
      "1/2 cup romaine lettuce, chopped",
      "1/4 cup cherry tomatoes, halved",
      "1/4 cup ranch dressing",
      "1/4 cup shredded cheddar cheese",
    ],
    instructions: [
      "Lay tortillas flat and spread ranch dressing evenly.",
      "Layer lettuce, tomatoes, chicken, and cheese in the center.",
      "Fold the sides of the tortilla inward and roll tightly.",
      "Slice in half and serve immediately.",
    ],
    tip1_title: "Grill Perfectly",
    tip1_content: "Grill chicken to 165°F for safety.",
    tip2_title: "Crisp Veggies",
    tip2_content: "Use crisp, fresh veggies for the best texture.",
    tip3_title: "Wrap Tightly",
    tip3_content: "Roll tightly to prevent filling from spilling.",
    variation1_title: "Buffalo Chicken Wrap",
    variation1_content: "Toss chicken in buffalo sauce for a spicy version.",
    variation1_image: "../../../Public/assets/RecipeDetails/chicken3.jpg",
    variation2_title: "BBQ Chicken Wrap",
    variation2_content: "Use BBQ sauce instead of ranch.",
    variation2_image: "../../../Public/assets/RecipeDetails/chicken4.jpg",
    variation3_title: "Veggie Ranch Wrap",
    variation3_content: "Skip chicken for a vegetarian option.",
    variation3_image: "../../../Public/assets/RecipeDetails/chicken5.jpg",
  },
  {
    id: 5,
    recipe_title: "Tuna Mix Salad",
    author_name: "Lisa Brown",
    publish_date: "April 18, 2025",
    time: "10 mins",
    chill_time: "30 mins",
    category: "Lunch",
    main_image: "../../../Public/assets/RecipeDetails/tuna1.webp",
    instruction_image: "../../../Public/assets/RecipeDetails/tuna2.jpg",
    calories: "220",
    protein: "15g",
    carbohydrates: "10g",
    fat: "14g",
    sugars: "3g",
    calcium: "8%",
    nutrition_note: "Values are per serving (1 cup).",
    recipe_description:
      "A creamy and flavorful tuna salad with crunchy celery and pickles, perfect for sandwiches or as a dip.",
    point_item1: "High Protein",
    point_item2: "Make-Ahead",
    point_item3: "Versatile",
    point_item4: "Budget-Friendly",
    ingredients: [
      "2 cans (5 oz each) tuna, drained",
      "1/4 cup mayonnaise",
      "1/4 cup celery, diced",
      "2 tbsp pickles, diced",
      "1 tbsp lemon juice",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Drain tuna and flake into a bowl.",
      "Add mayonnaise, celery, pickles, and lemon juice.",
      "Mix until well combined and season with salt and pepper.",
      "Chill for 30 minutes to let flavors meld.",
      "Serve on bread, crackers, or lettuce leaves.",
    ],
    tip1_title: "Drain Well",
    tip1_content: "Remove excess liquid from tuna for best texture.",
    tip2_title: "Add Crunch",
    tip2_content: "Include celery or apples for extra texture.",
    tip3_title: "Chill Time",
    tip3_content: "Chilling enhances flavor.",
    variation1_title: "Avocado Tuna Salad",
    variation1_content: "Add mashed avocado for creaminess.",
    variation1_image: "../../../Public/assets/RecipeDetails/tuna3.webp",
    variation2_title: "Spicy Tuna Salad",
    variation2_content: "Mix in hot sauce or jalapeños.",
    variation2_image: "../../../Public/assets/RecipeDetails/tuna4.webp",
    variation3_title: "Mediterranean Tuna Salad",
    variation3_content: "Add olives and feta cheese.",
    variation3_image: "../../../Public/assets/RecipeDetails/tuna5.jpg",
  },
  {
    id: 6,
    recipe_title: "Strawberry and Cherry Pancakes",
    author_name: "Olivia Davis",
    publish_date: "April 20, 2025",
    time: "20 mins",
    chill_time: "0 mins",
    category: "Breakfast",
    main_image: "../../../Public/assets/RecipeDetails/strawberry1.jpg",
    instruction_image: "../../../Public/assets/RecipeDetails/strawberry2.jpg",
    calories: "280",
    protein: "6g",
    carbohydrates: "40g",
    fat: "10g",
    sugars: "15g",
    calcium: "12%",
    nutrition_note: "Values are per serving (2 pancakes).",
    recipe_description:
      "Fluffy pancakes loaded with fresh strawberries and cherries, perfect for a sweet breakfast treat.",
    point_item1: "Fruity Flavor",
    point_item2: "Kid-Friendly",
    point_item3: "Quick Prep",
    point_item4: "Great for Brunch",
    ingredients: [
      "1 cup all-purpose flour",
      "1 cup milk",
      "1 egg",
      "1/2 cup strawberries, chopped",
      "1/2 cup cherries, pitted and chopped",
      "2 tbsp sugar",
      "2 tsp baking powder",
      "Butter for cooking",
    ],
    instructions: [
      "Mix flour, sugar, and baking powder in a bowl.",
      "Whisk in milk and egg until smooth.",
      "Fold in strawberries and cherries.",
      "Heat a skillet with butter and pour 1/4 cup batter per pancake.",
      "Cook until bubbles form, flip, and cook until golden.",
    ],
    tip1_title: "Fresh Fruit",
    tip1_content: "Use ripe, fresh fruit for best flavor.",
    tip2_title: "Non-Stick Pan",
    tip2_content: "Use a non-stick skillet for easy flipping.",
    tip3_title: "Keep Warm",
    tip3_content: "Keep pancakes warm in a low oven.",
    variation1_title: "Blueberry Pancakes",
    variation1_content: "Swap strawberries and cherries for blueberries.",
    variation1_image: "../../../Public/assets/RecipeDetails/strawberry3.webp",
    variation2_title: "Chocolate Chip Pancakes",
    variation2_content: "Add chocolate chips for extra sweetness.",
    variation2_image: "../../../Public/assets/RecipeDetails/strawberry4.jpg",
    variation3_title: "Banana Pancakes",
    variation3_content: "Add mashed banana for a tropical twist.",
    variation3_image: "../../../Public/assets/RecipeDetails/strawberry5.jpg",
  },
  {
    id: 7,
    recipe_title: "Fruits",
    author_name: "Amr Khaled",
    publish_date: "April 22, 2025",
    time: "15 mins",
    chill_time: "0 mins",
    category: "Breakfast",
    main_image: "../../../Public/assets/RecipeDetails/fruits1.jpg",
    instruction_image: "../../../Public/assets/RecipeDetails/fruits2.jpg",
    calories: "150",
    protein: "2g",
    carbohydrates: "35g",
    fat: "0g",
    sugars: "25g",
    calcium: "10%",
    nutrition_note: "Values are per serving (1 cup).",
    recipe_description:
      "A refreshing mix of seasonal fruits, perfect for a healthy breakfast or snack.",
    point_item1: "Fresh Ingredients",
    point_item2: "Vitamin Rich",
    point_item3: "Quick Prep",
    point_item4: "Kid-Friendly",
    ingredients: [
      "1 cup strawberries, sliced",
      "1 cup blueberries",
      "1 banana, sliced",
      "1/2 cup grapes",
      "1 tbsp honey",
      "1 tsp lemon juice",
    ],
    instructions: [
      "Wash all fruits thoroughly.",
      "Slice strawberries and banana.",
      "Combine all fruits in a bowl.",
      "Drizzle with honey and lemon juice.",
      "Toss gently and serve chilled.",
    ],
    tip1_title: "Seasonal Fruits",
    tip1_content: "Use fruits that are in season for best flavor.",
    tip2_title: "Presentation",
    tip2_content: "Serve in a clear glass bowl to showcase the colors.",
    tip3_title: "Storage",
    tip3_content:
      "Best consumed immediately but can be refrigerated for 2 hours.",
    variation1_title: "Tropical Fruit Mix",
    variation1_content: "Add mango and pineapple for tropical flavors.",
    variation1_image: "../../../Public/assets/RecipeDetails/fruits3.jpg",
    variation2_title: "Berry Medley",
    variation2_content: "Use only berries for an antioxidant-rich version.",
    variation2_image: "../../../Public/assets/RecipeDetails/fruits4.avif",
    variation3_title: "Citrus Salad",
    variation3_content:
      "Add orange segments and grapefruit for a citrus twist.",
    variation3_image: "../../../Public/assets/RecipeDetails/fruits5.jpg",
  },
  {
    id: 8,
    recipe_title: "Fries and Burger",
    author_name: "Anas Refaei",
    publish_date: "April 24, 2025",
    time: "30 mins",
    chill_time: "0 mins",
    category: "Lunch",
    main_image: "../../../Public/assets/RecipeDetails/burger1.png",
    instruction_image: "../../../Public/assets/RecipeDetails/burger2.jpg",
    calories: "650",
    protein: "25g",
    carbohydrates: "45g",
    fat: "35g",
    sugars: "8g",
    calcium: "15%",
    nutrition_note: "Values are per serving (1 burger with fries).",
    recipe_description:
      "Classic beef burger with crispy fries, a satisfying meal for any occasion.",
    point_item1: "Comfort Food",
    point_item2: "Crowd Pleaser",
    point_item3: "Customizable",
    point_item4: "Perfect for Gatherings",
    ingredients: [
      "1 lb ground beef",
      "4 burger buns",
      "1 tsp salt",
      "1 tsp pepper",
      "1 tsp garlic powder",
      "4 slices cheddar cheese",
      "1 large potato, cut into fries",
      "Oil for frying",
      "Lettuce, tomato, onion for garnish",
    ],
    instructions: [
      "Mix ground beef with salt, pepper and garlic powder.",
      "Form into 4 patties and grill for 5 minutes per side.",
      "Add cheese slices during last minute of cooking.",
      "Cut potato into fries and fry until golden brown.",
      "Assemble burgers with buns and desired toppings.",
      "Serve hot with fries.",
    ],
    tip1_title: "Patty Thickness",
    tip1_content: "Make patties slightly larger than buns as they shrink.",
    tip2_title: "Cheese Melt",
    tip2_content: "Cover burger with lid to help cheese melt completely.",
    tip3_title: "Fry Crispiness",
    tip3_content: "Double fry fries for extra crispiness.",
    variation1_title: "Chicken Burger",
    variation1_content:
      "Use ground chicken instead of beef for lighter option.",
    variation1_image: "../../../Public/assets/RecipeDetails/burger3.jpg",
    variation2_title: "Veggie Burger",
    variation2_content: "Use black bean patties for vegetarian version.",
    variation2_image: "../../../Public/assets/RecipeDetails/burger4.jpg",
    variation3_title: "Bacon Burger",
    variation3_content: "Add crispy bacon strips for extra flavor.",
    variation3_image: "../../../Public/assets/RecipeDetails/burger5.avif",
  },
  {
    id: 9,
    recipe_title: "Cooked Seafoods",
    author_name: "Abdullah Islam",
    publish_date: "April 26, 2025",
    time: "25 mins",
    chill_time: "0 mins",
    category: "Dinner",
    main_image: "../../../Public/assets/RecipeDetails/seafood1.webp",
    instruction_image: "../../../Public/assets/RecipeDetails/seafood2.jpg",
    calories: "320",
    protein: "30g",
    carbohydrates: "15g",
    fat: "18g",
    sugars: "3g",
    calcium: "20%",
    nutrition_note: "Values are per serving (1 plate).",
    recipe_description:
      "Delicate seafood medley cooked with garlic butter, perfect for a light yet satisfying dinner.",
    point_item1: "High Protein",
    point_item2: "Omega-3 Rich",
    point_item3: "Elegant Presentation",
    point_item4: "Quick Cooking",
    ingredients: [
      "1 lb mixed seafood (shrimp, scallops, mussels)",
      "3 tbsp butter",
      "3 garlic cloves, minced",
      "1/4 cup white wine",
      "1 tbsp lemon juice",
      "2 tbsp chopped parsley",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Clean and pat dry all seafood.",
      "Melt butter in pan and sauté garlic until fragrant.",
      "Add seafood and cook for 2-3 minutes.",
      "Deglaze with white wine and lemon juice.",
      "Season with salt and pepper.",
      "Garnish with parsley and serve immediately.",
    ],
    tip1_title: "Freshness Check",
    tip1_content: "Ensure seafood smells fresh like the ocean, not fishy.",
    tip2_title: "Don't Overcook",
    tip2_content: "Seafood cooks quickly - remove from heat as soon as opaque.",
    tip3_title: "Wine Substitute",
    tip3_content: "Use chicken broth if avoiding alcohol.",
    variation1_title: "Spicy Seafood",
    variation1_content: "Add red pepper flakes for heat.",
    variation1_image: "../../../Public/assets/RecipeDetails/seafood3.jpg",
    variation2_title: "Creamy Seafood",
    variation2_content: "Stir in heavy cream for rich sauce.",
    variation2_image: "../../../Public/assets/RecipeDetails/seafood4.jpg",
    variation3_title: "Lemon Herb Seafood",
    variation3_content: "Add extra lemon zest and fresh herbs.",
    variation3_image: "../../../Public/assets/RecipeDetails/seafood5.webp",
  },
  {
    id: 10,
    recipe_title: "Fries With Leaves",
    author_name: "Zyad Ashraf",
    publish_date: "April 28, 2025",
    time: "20 mins",
    chill_time: "0 mins",
    category: "Appetizer",
    main_image: "../../../Public/assets/RecipeDetails/fries1.jpg",
    instruction_image: "../../../Public/assets/RecipeDetails/fries2.jpeg",
    calories: "280",
    protein: "5g",
    carbohydrates: "35g",
    fat: "15g",
    sugars: "2g",
    calcium: "8%",
    nutrition_note: "Values are per serving (1 plate).",
    recipe_description:
      "Crispy fries served with fresh greens and special dipping sauce, a perfect starter.",
    point_item1: "Crunchy Texture",
    point_item2: "Flavorful Dip",
    point_item3: "Quick to Make",
    point_item4: "Great for Sharing",
    ingredients: [
      "2 large potatoes, cut into fries",
      "2 cups mixed salad greens",
      "1/2 cup mayonnaise",
      "1 tbsp ketchup",
      "1 tsp paprika",
      "Oil for frying",
      "Salt to taste",
    ],
    instructions: [
      "Cut potatoes into even-sized fries.",
      "Fry in hot oil until golden and crispy.",
      "Drain on paper towels and season with salt.",
      "Mix mayonnaise, ketchup and paprika for sauce.",
      "Arrange fries on plate with greens.",
      "Serve with dipping sauce.",
    ],
    tip1_title: "Even Cutting",
    tip1_content: "Cut fries same size for even cooking.",
    tip2_title: "Double Fry",
    tip2_content: "Fry twice for extra crispiness.",
    tip3_title: "Greens Freshness",
    tip3_content: "Use crisp, fresh greens for best texture.",
    variation1_title: "Cheese Fries",
    variation1_content: "Top with melted cheese and bacon bits.",
    variation1_image: "../../../Public/assets/RecipeDetails/fries3.jpg",
    variation2_title: "Sweet Potato Fries",
    variation2_content: "Use sweet potatoes for healthier version.",
    variation2_image: "../../../Public/assets/RecipeDetails/fries4.webp",
    variation3_title: "Spicy Fries",
    variation3_content: "Toss with chili powder and lime juice.",
    variation3_image: "../../../Public/assets/RecipeDetails/fries5.jpg",
  },
  {
    id: 11,
    recipe_title: "Sliced Cake",
    author_name: "Beshr",
    publish_date: "April 30, 2025",
    time: "45 mins",
    chill_time: "30 mins",
    category: "Dessert",
    main_image: "../../../Public/assets/RecipeDetails/cake1.jpg",
    instruction_image: "../../../Public/assets/RecipeDetails/cake2.jpeg",
    calories: "350",
    protein: "5g",
    carbohydrates: "50g",
    fat: "15g",
    sugars: "35g",
    calcium: "6%",
    nutrition_note: "Values are per serving (1 slice).",
    recipe_description:
      "Moist vanilla cake with creamy frosting, beautifully decorated and perfect for celebrations.",
    point_item1: "Celebration Worthy",
    point_item2: "Moist Texture",
    point_item3: "Beautiful Presentation",
    point_item4: "Crowd Pleaser",
    ingredients: [
      "2 cups all-purpose flour",
      "1 1/2 cups sugar",
      "3 eggs",
      "1 cup milk",
      "1/2 cup butter, softened",
      "2 tsp vanilla extract",
      "2 tsp baking powder",
      "1/4 tsp salt",
      "2 cups frosting of choice",
    ],
    instructions: [
      "Preheat oven to 350°F and grease cake pans.",
      "Cream butter and sugar until light and fluffy.",
      "Add eggs one at a time, then vanilla.",
      "Alternate adding dry ingredients and milk.",
      "Bake for 25-30 minutes until golden.",
      "Cool completely before frosting.",
      "Decorate as desired.",
    ],
    tip1_title: "Room Temperature",
    tip1_content: "Use room temperature ingredients for even mixing.",
    tip2_title: "Don't Overmix",
    tip2_content: "Mix just until combined to avoid dense cake.",
    tip3_title: "Cooling Time",
    tip3_content: "Let cake cool completely before frosting.",
    variation1_title: "Chocolate Cake",
    variation1_content: "Add cocoa powder for chocolate version.",
    variation1_image: "../../../Public/assets/RecipeDetails/cake3.webp",
    variation2_title: "Lemon Cake",
    variation2_content: "Add lemon zest and juice for citrus flavor.",
    variation2_image: "../../../Public/assets/RecipeDetails/cake4.jpg",
    variation3_title: "Red Velvet",
    variation3_content: "Make red velvet with cream cheese frosting.",
    variation3_image: "../../../Public/assets/RecipeDetails/cake5.jpeg",
  },
  {
    id: 12,
    recipe_title: "Spaghetti Sauce",
    author_name: "Alex Martin",
    publish_date: "May 2, 2025",
    time: "40 mins",
    chill_time: "0 mins",
    category: "Dinner",
    main_image: "../../../Public/assets/RecipeDetails/spaghetti1.webp",
    instruction_image: "../../../Public/assets/RecipeDetails/spaghetti2.jpg",
    calories: "280",
    protein: "12g",
    carbohydrates: "35g",
    fat: "10g",
    sugars: "8g",
    calcium: "10%",
    nutrition_note: "Values are per serving (1 plate).",
    recipe_description:
      "Rich and flavorful tomato-based sauce with herbs, perfect over al dente spaghetti.",
    point_item1: "Comfort Food",
    point_item2: "Family Favorite",
    point_item3: "Freezer Friendly",
    point_item4: "Versatile Base",
    ingredients: [
      "1 lb ground beef",
      "1 onion, diced",
      "3 garlic cloves, minced",
      "28 oz canned tomatoes",
      "2 tbsp tomato paste",
      "1 tsp sugar",
      "1 tsp dried basil",
      "1 tsp dried oregano",
      "Salt and pepper to taste",
      "1/4 cup fresh parsley, chopped",
    ],
    instructions: [
      "Brown ground beef with onion and garlic.",
      "Add tomatoes, paste, sugar and herbs.",
      "Simmer for 30 minutes, stirring occasionally.",
      "Season with salt and pepper.",
      "Stir in fresh parsley before serving.",
      "Serve over cooked spaghetti.",
    ],
    tip1_title: "Simmer Time",
    tip1_content: "Longer simmering develops deeper flavor.",
    tip2_title: "Fresh Herbs",
    tip2_content: "Use fresh basil if available for brighter taste.",
    tip3_title: "Meat Options",
    tip3_content: "Try Italian sausage for different flavor profile.",
    variation1_title: "Vegetarian Sauce",
    variation1_content:
      "Replace ground beef with mushrooms and lentils for a hearty vegetarian version.",
    variation1_image: "../../../Public/assets/RecipeDetails/spaghetti3.jpg",
    variation2_title: "Spicy Arrabbiata",
    variation2_content: "Add 1 tsp red pepper flakes for a spicy kick.",
    variation2_image: "../../../Public/assets/RecipeDetails/spaghetti4.jpg",
    variation3_title: "Creamy Tomato",
    variation3_content:
      "Stir in 1/2 cup heavy cream at the end for a rich, creamy texture.",
    variation3_image: "../../../Public/assets/RecipeDetails/spaghetti5.jpeg",
  },
  {
    id: 13,
    recipe_title: "Grilled Chicken",
    author_name: "Chef Alex",
    publish_date: "April 18, 2025",
    time: "30 mins",
    chill_time: "10 mins",
    category: "Main Course",
    main_image: "../../../Public/assets/RecipeDetails/grilled1.webp",
    instruction_image: "../../../Public/assets/RecipeDetails/grilled2.jpeg",
    calories: "400",
    protein: "35g",
    carbohydrates: "5g",
    fat: "25g",
    sugars: "2g",
    calcium: "8%",
    nutrition_note: "Values are per serving (1 chicken breast).",
    recipe_description:
      "Juicy and flavorful grilled chicken with a perfect char, seasoned with herbs and spices.",
    point_item1: "High Protein",
    point_item2: "Simple Ingredients",
    point_item3: "Great for Meal Prep",
    point_item4: "Versatile",
    ingredients: [
      "4 boneless, skinless chicken breasts",
      "2 tbsp olive oil",
      "1 tsp garlic powder",
      "1 tsp paprika",
      "1 tsp dried oregano",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Preheat grill to medium-high heat.",
      "Mix olive oil and spices in a bowl.",
      "Coat chicken breasts with the spice mixture.",
      "Grill for 6-7 minutes per side until internal temperature reaches 165°F.",
      "Let rest for 5 minutes before serving.",
    ],
    tip1_title: "Even Thickness",
    tip1_content: "Pound chicken to even thickness for consistent cooking.",
    tip2_title: "Marinade Time",
    tip2_content: "Marinate for at least 30 minutes for more flavor.",
    tip3_title: "Grill Marks",
    tip3_content: "Don't move chicken too soon to get perfect grill marks.",
    variation1_title: "Lemon Herb Chicken",
    variation1_content: "Add lemon zest and fresh herbs for a bright flavor.",
    variation1_image: "../../../Public/assets/RecipeDetails/grilled3.jpeg",
    variation2_title: "Spicy Grilled Chicken",
    variation2_content: "Add cayenne pepper for a spicy kick.",
    variation2_image: "../../../Public/assets/RecipeDetails/grilled4.jpeg",
    variation3_title: "BBQ Chicken",
    variation3_content:
      "Brush with BBQ sauce during last 5 minutes of grilling.",
    variation3_image: "../../../Public/assets/RecipeDetails/grilled5.jpeg",
  },
  {
    id: 14,
    recipe_title: "Fried Potatoes",
    author_name: "Chef Maria",
    publish_date: "April 20, 2025",
    time: "25 mins",
    chill_time: "0 mins",
    category: "Side Dish",
    main_image: "../../../Public/assets/RecipeDetails/potato1.jpg",
    instruction_image: "../../../Public/assets/RecipeDetails/potato2.jpg",
    calories: "300",
    protein: "4g",
    carbohydrates: "40g",
    fat: "15g",
    sugars: "3g",
    calcium: "6%",
    nutrition_note: "Values are per serving (1 cup).",
    recipe_description:
      "Crispy golden fried potatoes with a fluffy interior, seasoned to perfection.",
    point_item1: "Comfort Food",
    point_item2: "Crowd Pleaser",
    point_item3: "Easy to Make",
    point_item4: "Versatile Side",
    ingredients: [
      "4 large russet potatoes, peeled and diced",
      "3 tbsp vegetable oil",
      "1 tsp garlic powder",
      "1 tsp onion powder",
      "1/2 tsp paprika",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Rinse diced potatoes and pat dry thoroughly.",
      "Heat oil in a large skillet over medium-high heat.",
      "Add potatoes and cook without stirring for 5 minutes to brown one side.",
      "Stir and continue cooking until golden and crispy, about 15 minutes.",
      "Season with spices and serve hot.",
    ],
    tip1_title: "Dry Potatoes",
    tip1_content:
      "Ensure potatoes are dry before frying for maximum crispiness.",
    tip2_title: "Oil Temperature",
    tip2_content: "Keep oil hot but not smoking to prevent burning.",
    tip3_title: "Seasoning Timing",
    tip3_content: "Season at the end to prevent spices from burning.",
    variation1_title: "Garlic Parmesan Potatoes",
    variation1_content:
      "Toss with minced garlic and grated parmesan after frying.",
    variation1_image: "../../../Public/assets/RecipeDetails/potato3.jpg",
    variation2_title: "Spicy Potatoes",
    variation2_content: "Add chili flakes or cayenne pepper for heat.",
    variation2_image: "../../../Public/assets/RecipeDetails/potato4.jpeg",
    variation3_title: "Herb Potatoes",
    variation3_content: "Mix in fresh rosemary or thyme for aromatic flavor.",
    variation3_image: "../../../Public/assets/RecipeDetails/potato5.jpg",
  },
];

const params = new URLSearchParams(window.location.search);
const recipeId = parseInt(params.get("id"));

const selectedRecipe = recipes.find((recipe) => recipe.id === recipeId);

document.querySelector(".recipe-title").textContent =
  selectedRecipe.recipe_title;

document.querySelector(".author-name").textContent = selectedRecipe.author_name;
document.querySelector(".publish-date").textContent =
  selectedRecipe.publish_date;

document.querySelectorAll(".time")[0].textContent = selectedRecipe.time;
document.querySelectorAll(".time")[1].textContent = selectedRecipe.chill_time;

document.querySelector(".header-item:last-child span").textContent =
  selectedRecipe.category;

document.querySelector(".main-image img").src = selectedRecipe.main_image;

document.querySelector(".instruction-image img").src =
  selectedRecipe.instruction_image;

document.querySelector(
  ".nutrition-info ul li:nth-child(1) span:last-child"
).textContent = selectedRecipe.calories;
document.querySelector(
  ".nutrition-info ul li:nth-child(2) span:last-child"
).textContent = selectedRecipe.protein;
document.querySelector(
  ".nutrition-info ul li:nth-child(3) span:last-child"
).textContent = selectedRecipe.carbohydrates;
document.querySelector(
  ".nutrition-info ul li:nth-child(4) span:last-child"
).textContent = selectedRecipe.fat;
document.querySelector(
  ".nutrition-info ul li:nth-child(5) span:last-child"
).textContent = selectedRecipe.sugars;
document.querySelector(
  ".nutrition-info ul li:nth-child(6) span:last-child"
).textContent = selectedRecipe.calcium;
document.querySelector(".nutrition-note").textContent =
  selectedRecipe.nutrition_note;

document.querySelector(".recipe-description p").textContent =
  selectedRecipe.recipe_description;

document.querySelector(".point-item1 span").textContent =
  selectedRecipe.point_item1;
document.querySelector(".point-item2 span").textContent =
  selectedRecipe.point_item2;
document.querySelector(".point-item3 span").textContent =
  selectedRecipe.point_item3;
document.querySelector(".point-item4 span").textContent =
  selectedRecipe.point_item4;

const ingredientsList = document.querySelector(".ingredients-list");
ingredientsList.innerHTML = "<h2>Ingredients</h2>";
selectedRecipe.ingredients.forEach((ingredient, index) => {
  const div = document.createElement("div");
  div.className = "ingredient-item";
  div.innerHTML = `
      <input type="checkbox" id="ing${index + 1}">
      <label for="ing${index + 1}">${ingredient}</label>
    `;
  ingredientsList.appendChild(div);
});

const instructionsList = document.querySelector(".instructions-list");
instructionsList.innerHTML = "";
selectedRecipe.instructions.forEach((instruction, index) => {
  const div = document.createElement("div");
  div.className = "instruction-item";
  div.innerHTML = `
      <span class="number">${index + 1}.</span>
      <span class="text">${instruction}</span>
    `;
  instructionsList.appendChild(div);
});

document.querySelector(".tip-item:nth-child(1) .tip-content h3").textContent =
  selectedRecipe.tip1_title;
document.querySelector(".tip-item:nth-child(1) .tip-content p").textContent =
  selectedRecipe.tip1_content;
document.querySelector(".tip-item:nth-child(2) .tip-content h3").textContent =
  selectedRecipe.tip2_title;
document.querySelector(".tip-item:nth-child(2) .tip-content p").textContent =
  selectedRecipe.tip2_content;
document.querySelector(".tip-item:nth-child(3) .tip-content h3").textContent =
  selectedRecipe.tip3_title;
document.querySelector(".tip-item:nth-child(3) .tip-content p").textContent =
  selectedRecipe.tip3_content;

document.querySelector(".variation-card:nth-child(1) img").src =
  selectedRecipe.variation1_image;
document.querySelector(".variation-card:nth-child(1) h3").textContent =
  selectedRecipe.variation1_title;
document.querySelector(".variation-card:nth-child(1) p").textContent =
  selectedRecipe.variation1_content;
document.querySelector(".variation-card:nth-child(2) img").src =
  selectedRecipe.variation2_image;
document.querySelector(".variation-card:nth-child(2) h3").textContent =
  selectedRecipe.variation2_title;
document.querySelector(".variation-card:nth-child(2) p").textContent =
  selectedRecipe.variation2_content;
document.querySelector(".variation-card:nth-child(3) img").src =
  selectedRecipe.variation3_image;
document.querySelector(".variation-card:nth-child(3) h3").textContent =
  selectedRecipe.variation3_title;
document.querySelector(".variation-card:nth-child(3) p").textContent =
  selectedRecipe.variation3_content;
